// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wedjat.MiniMES;

#nullable disable

namespace Wedjat.MiniMES.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20251201074656_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wedjat.MiniMES.Model.CompanyEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间（自动生成）");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("员工姓名");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("员工密码（建议加密存储）");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间（修改时自动更新）");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("员工工号（业务唯一）");

                    b.HasKey("Id");

                    b.HasIndex("WorkId")
                        .IsUnique()
                        .HasDatabaseName("IX_CompanyEmployee_WorkId");

                    b.ToTable("CompanyEmployee");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesInspectionDefect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("缺陷数量（默认0）");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("关联的缺陷编码（逻辑外键）");

                    b.Property<string>("InspectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("关联的检测编号（逻辑外键）");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DefectCode");

                    b.HasIndex("InspectionCode");

                    b.ToTable("MesInspectionDefect");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesPCB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PCBCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("PCB编号（业务唯一）");

                    b.Property<string>("PCBName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("PCB名称");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PCBCode")
                        .IsUnique()
                        .HasDatabaseName("IX_MesPCB_PCBCode");

                    b.ToTable("MesPCB");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesPCBDefect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("缺陷编码（唯一标识）");

                    b.Property<string>("DefectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("缺陷名称");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("缺陷描述");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PCBCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("关联的PCB编号（逻辑外键）");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PCBCode", "DefectCode")
                        .IsUnique()
                        .HasDatabaseName("IX_MesPCBDefect_PCBCode_DefectCode");

                    b.ToTable("MesPCBDefect");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesPCBInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InspectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("检测编号（业务唯一）");

                    b.Property<DateTime>("InspectionTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("检测时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsQualified")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否合格（true=合格，false=不合格）");

                    b.Property<string>("PCBCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("关联的PCB编号（逻辑外键）");

                    b.Property<string>("PCBSN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("单个PCB的二维码标识（唯一追溯）");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("产线名称");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("检测员工号（关联CompanyEmployee.WorkId）");

                    b.Property<string>("WorkOrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("关联的工单编号（逻辑外键）");

                    b.HasKey("Id");

                    b.HasIndex("InspectionCode")
                        .IsUnique()
                        .HasDatabaseName("IX_MesPCBInspection_InspectionCode");

                    b.HasIndex("PCBCode");

                    b.HasIndex("WorkId");

                    b.HasIndex("WorkOrderCode");

                    b.ToTable("MesPCBInspection");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesWorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("工单状态（Pending/Processing/Completed/Canceled）");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkOrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("工单编号（业务唯一）");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderCode")
                        .IsUnique()
                        .HasDatabaseName("IX_MesWorkOrder_WorkOrderCode");

                    b.ToTable("MesWorkOrder");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesWorkOrderPCB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompleteQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("已完成数量（默认0）");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PCBCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("关联的PCB编号（逻辑外键）");

                    b.Property<int>("PlanQuantity")
                        .HasColumnType("int")
                        .HasComment("计划生产数量");

                    b.Property<int>("QualifiedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("合格数量（默认0）");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkOrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("关联的工单编号（逻辑外键）");

                    b.HasKey("Id");

                    b.HasIndex("PCBCode");

                    b.HasIndex("WorkOrderCode");

                    b.ToTable("MesWorkOrderPCB");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesInspectionDefect", b =>
                {
                    b.HasOne("Wedjat.MiniMES.Model.MesPCBDefect", "Defect")
                        .WithMany("InspectionDefects")
                        .HasForeignKey("DefectCode")
                        .HasPrincipalKey("DefectCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Wedjat.MiniMES.Model.MesPCBInspection", "Inspection")
                        .WithMany("DetectedDefects")
                        .HasForeignKey("InspectionCode")
                        .HasPrincipalKey("InspectionCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Defect");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesPCBDefect", b =>
                {
                    b.HasOne("Wedjat.MiniMES.Model.MesPCB", "PCB")
                        .WithMany("Defects")
                        .HasForeignKey("PCBCode")
                        .HasPrincipalKey("PCBCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PCB");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesPCBInspection", b =>
                {
                    b.HasOne("Wedjat.MiniMES.Model.MesPCB", "PCB")
                        .WithMany("Inspections")
                        .HasForeignKey("PCBCode")
                        .HasPrincipalKey("PCBCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Wedjat.MiniMES.Model.CompanyEmployee", "Inspector")
                        .WithMany("Inspections")
                        .HasForeignKey("WorkId")
                        .HasPrincipalKey("WorkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Wedjat.MiniMES.Model.MesWorkOrder", "WorkOrder")
                        .WithMany("Inspections")
                        .HasForeignKey("WorkOrderCode")
                        .HasPrincipalKey("WorkOrderCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Inspector");

                    b.Navigation("PCB");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesWorkOrderPCB", b =>
                {
                    b.HasOne("Wedjat.MiniMES.Model.MesPCB", "PCB")
                        .WithMany("WorkOrderPCBs")
                        .HasForeignKey("PCBCode")
                        .HasPrincipalKey("PCBCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Wedjat.MiniMES.Model.MesWorkOrder", "WorkOrder")
                        .WithMany("WorkOrderPCBs")
                        .HasForeignKey("WorkOrderCode")
                        .HasPrincipalKey("WorkOrderCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PCB");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.CompanyEmployee", b =>
                {
                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesPCB", b =>
                {
                    b.Navigation("Defects");

                    b.Navigation("Inspections");

                    b.Navigation("WorkOrderPCBs");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesPCBDefect", b =>
                {
                    b.Navigation("InspectionDefects");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesPCBInspection", b =>
                {
                    b.Navigation("DetectedDefects");
                });

            modelBuilder.Entity("Wedjat.MiniMES.Model.MesWorkOrder", b =>
                {
                    b.Navigation("Inspections");

                    b.Navigation("WorkOrderPCBs");
                });
#pragma warning restore 612, 618
        }
    }
}
